/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego Luján García (https://sketchfab.com/diegoluga)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/ab11ebff89224f03bd75efede1164cf6
title: Male Full Body Ecorche
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.hip} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.shoulder} geometry={nodes.mesh_1.geometry} />
        <mesh material={materials.calf_and_low} geometry={nodes.mesh_2.geometry} />
        <mesh material={materials.back_thigh} geometry={nodes.mesh_3.geometry} />
        <mesh material={materials.nose} geometry={nodes.mesh_4.geometry} />
        <mesh material={materials.back} geometry={nodes.mesh_5.geometry} />
        <mesh material={materials.head} geometry={nodes.mesh_6.geometry} />
        <mesh material={materials.front_thigh} geometry={nodes.mesh_7.geometry} />
        <mesh material={materials.neck} geometry={nodes.mesh_8.geometry} />
        <mesh material={materials.hand_tissue} geometry={nodes.mesh_9.geometry} />
        <mesh material={materials.chest_and_abs} geometry={nodes.mesh_10.geometry} />
        <mesh material={materials.front_lower_leg} geometry={nodes.mesh_11.geometry} />
        <mesh material={materials.inner_upper_thigh} geometry={nodes.mesh_12.geometry} />
        <mesh material={materials.feet_finger} geometry={nodes.mesh_13.geometry} />
        <mesh material={materials.lowerForearm} geometry={nodes.mesh_14.geometry} />
        <mesh material={materials.biceps} geometry={nodes.mesh_15.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
